### PR TITLE
[microTVM] Update support for ARMv7m intrinsic #8990

### PR DESCRIPTION
**Pull request by sergey-grovety**
Model for test case.

### CODE REVIEW

**Comment by mehrdadh** [comment]
@sergey-grovety thanks for the PR. Could you please move the model to under `testdata/microTVM/model` directory?

**Comment by areusch** [comment]
@sergey-grovety can you address @mehrdadh comment?

**Comment by sergey-grovety** [comment]
Done.

**Review by mehrdadh — APPROVED** [review]
LGTM! Thanks.

**Pull request merged**
