### PR TITLE
microTVM AOT Zephyr Demo Test Data

### PR DESCRIPTION
**Pull request by mehrdadh**
Adding a float32 image sample for image classification model.

### CODE REVIEW

**Comment by mehrdadh** [comment]
@tqchen @areusch

**Review by areusch — APPROVED** [review]

**Comment by areusch** [comment]
for tvm#8075

**Review by areusch — APPROVED** [review]

**Comment by areusch** [comment]
@tqchen seems I still cannot merge

**Comment by mehrdadh** [comment]
Thanks @areusch!

**Pull request merged**
