### PR TITLE
Adreno documentation support file.

### PR DESCRIPTION
**Pull request by srkreddy1238**

### CODE REVIEW

**Comment by srkreddy1238** [comment]
I will increase the font sizes.

> * Actually, `Android JNI/Native` and `RTVM` are both just Android applications. So probably they shouldn't be separated to different blocks?

Technically they are same but, ```RTVM``` is a tool we are providing and other is some thing the end user will implement in the apps. I tried to show them the options here. I will try different presentation here.

**Comment by echuraev** [comment]
Thank you very much! Now it is much more readable. 
One more comment about the `RTVM`. 

I think this separation on two blocks may confuse. Because it looks like two different approaches to run but in fact they are the same.
image

I have some ideas here:
1. You can just add `RTVM` to the block with `Android JNI/Native` and in the description of this pipeline add more details about options how user can run something on Adreno.
2. You can write about `Android JNI` and `RTVM` in one visually separated block, for example:
image

What do you think about that?

**Review by echuraev — APPROVED** [review]
LGTM. Thanks

**Comment by echuraev** [comment]
@driazati Could you please take a look at this PR?

**Review by driazati — APPROVED** [review]
lgtm, it'd be preferable to have a `.png` vs a `.jpg` since this is a diagram but we can leave that for a follow up if necessary

**Pull request merged**
